return {
    "nvim-treesitter/nvim-treesitter",
    dependencies = {
        "nvim-treesitter/nvim-treesitter-textobjects",
        "nvim-treesitter/nvim-treesitter-context",
    },
    highlight = { enable = true },
    indent = { enable = true },
    opts = {
        ensure_installed = {
            "bash",
            "vimdoc",
            "html",
            "javascript",
            "json",
            "lua",
            "markdown",
            "markdown_inline",
            "python",
            "query",
            "regex",
            "tsx",
            "typescript",
            "vim",
            "yaml",
            "go",
            "dockerfile",
            "git_config",
            "jsdoc",
            "make",
            "toml",
            "sproto",
        },
    },
}
